{% set version = '0.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-threejs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/threejs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/threejs/threejs_{{ version }}.tar.gz
  sha256: 76c759c8b20fb34f4f7a01cbd1b961296e1f19f4df6dded69aae7f1bca80219c

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-crosstalk
    - r-htmlwidgets >=0.3.2
    - r-igraph >=1.0.0
  run:
    - r-base
    - r-base64enc
    - r-crosstalk
    - r-htmlwidgets >=0.3.2
    - r-igraph >=1.0.0

test:
  commands:
    - $R -e "library('threejs')"           # [not win]
    - "\"%R%\" -e \"library('threejs')\""  # [win]

about:
  home: https://bwlewis.github.io/rthreejs
  license: MIT
  summary: Create interactive 3D scatter plots, network plots, and globes using the 'three.js'
    visualization library (<https://threejs.org>).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: threejs
# Type: Package
# Title: Interactive 3D Scatter Plots, Networks and Globes
# Description: Create interactive 3D scatter plots, network plots, and globes using the 'three.js' visualization library (<https://threejs.org>).
# Version: 0.3.3
# Date: 2020-01-19
# Authors@R: c( person("B. W.", "Lewis", role=c("aut","cre","cph"), email="blewis@illposed.net"), person(given="Three.js authors", role="cph", comment="three.js library"), person(given="jQuery Foundation", role="cph", comment="jQuery library"), person("Alexey", "Stukalov", role=("ctb"), email="astukalov@gmail.com"), person("Yihui","Xie", role=("ctb"), email="xie@yihui.name"), person("Andreas", "Briese", role=("ctb"), email="ab@edutoolbox.de"), person("B.", "Thieurmel", role=("ctb"), email="bthieurmel@gmail.com") )
# URL: https://bwlewis.github.io/rthreejs
# BugReports: https://github.com/bwlewis/rthreejs/issues
# License: MIT + file LICENSE
# Depends: R (>= 3.0.0), igraph (>= 1.0.0)
# Imports: htmlwidgets (>= 0.3.2), base64enc, crosstalk, methods, stats
# Suggests: maps
# Enhances: knitr, shiny
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-01-21 15:03:57 UTC; blewis
# Author: B. W. Lewis [aut, cre, cph], Three.js authors [cph] (three.js library), jQuery Foundation [cph] (jQuery library), Alexey Stukalov [ctb], Yihui Xie [ctb], Andreas Briese [ctb], B. Thieurmel [ctb]
# Maintainer: B. W. Lewis <blewis@illposed.net>
# Repository: CRAN
# Date/Publication: 2020-01-21 15:50:03 UTC
