appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pMK2x44cCt7j35oRoGAN5RCHtS5NqSrugVipiklMScpIhBZqy7Qy9WmyDC1YPAwCj146JrPmSRifw/C8fr0kP/4vhP9h77pNAkzU21D+gRtqoQa1WWO2F8wwqhoMkwceXAF2vWM7MqVtj8g2Ycux4Uxplgz/Yl2rQzRKES3gWi51nar7/C/Z4zUJsoscKFMoVmlHSaog9e71rqu16IQv001Sk/7vbS9UeDqXwHvQWbfiLF7zOlojS6eCSepLYQ09h9NkfkVX9rO/q2+QJgB9ytuRTd3DwlZRdo+tnoCC4wLANMJoAjOwEtE1dvrbON1Cg3B+fETC6U+o4YmSYDjYskTz4lVfxi7f/TzXFQ9Hz/uLfskGCW2x8HgFpv9pBu+Npe5g6gzn73X2OCM4ouRwr/9wdu/0FcoOCb3LJuXvyefGlucMiBL/PIqDNfOIkRxKLkD8x/P0HZekREMA0qWdLMyhqXiaj12QP/P9RpPNGu8dfMmYyiPQ3adRnq6HB6kAvuc10dXX7sjKesf04RsLzi6PWMXirh55edkPuTnd0rdvlztfmqKYJybyAm97fTmNHM25gQn8GMB+b12QX/mCPHAv80yIjNRUUeJGjJ5/zH+P53nsO353T3DgmYpFFdBiVK0WAFM/rnedQNcrxQEWQ8q9eaF3M4yYlxLPOS2u6Q8=
conda_forge_output_validation: false
